// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _5I_jovanovicS_progettoInformatica.Migrations
{
    [DbContext(typeof(DbEsercizi))]
    [Migration("20220323194002_CreazioneDB")]
    partial class CreazioneDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Esercizio", b =>
                {
                    b.Property<int>("EsercizioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<int>("MuscoloID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeEsercizio")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroRipetizioni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondiRecupero")
                        .HasColumnType("INTEGER");

                    b.HasKey("EsercizioID");

                    b.HasIndex("MuscoloID");

                    b.ToTable("Esercizi");
                });

            modelBuilder.Entity("Muscolo", b =>
                {
                    b.Property<int>("MuscoloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.HasKey("MuscoloID");

                    b.ToTable("Muscoli");
                });

            modelBuilder.Entity("Esercizio", b =>
                {
                    b.HasOne("Muscolo", "Muscolo")
                        .WithMany("Esercizi")
                        .HasForeignKey("MuscoloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscolo");
                });

            modelBuilder.Entity("Muscolo", b =>
                {
                    b.Navigation("Esercizi");
                });
#pragma warning restore 612, 618
        }
    }
}
